version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
    ignore:
      # Not updating to JUnit 6 yet as it is not yet supported by VS Code
      - dependency-name: "junit-*"
        versions: [ "6.x" ]
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 10
