name: Build CDK Modules
on:
  pull_request:
    paths:
      - '.github/workflows/chunk-cdk.yaml'
      - '.github/workflows/chunk.yaml'
      - '.github/config/chunks.yaml'
      - 'code-style/checkstyle*.xml'
      - 'code-style/spotbugs*.xml'
      - 'java/pom.xml'
      - 'java/system-test/pom.xml'
      - 'java/cdk/**'
      - 'java/cdk-custom-resources/**'
      - 'java/cdk-environment/**'
      - 'java/system-test/system-test-cdk/**'
      - 'java/system-test/system-test-configuration/**'
      - 'java/system-test/system-test-data-generation/**'
      - 'java/system-test/system-test-dsl/**'
      - 'java/system-test/system-test-drivers/**'
      - 'java/system-test/system-test-suite/**'
      - 'java/bulk-import/bulk-import-starter/**'
      - 'java/clients/**'
      - 'java/ingest/ingest-batcher-submitter/**'
      - 'java/common/common-task/**'
      - 'java/ingest/ingest-batcher-store/**'
      - 'java/bulk-import/bulk-import-common/**'
      - 'java/splitter/splitter-core/**'
      - 'java/compaction/compaction-job-execution/**'
      - 'java/compaction/compaction-rust/**'
      - 'java/ingest/ingest-batcher-core/**'
      - 'java/query/query-runner/**'
      - 'java/garbage-collector/**'
      - 'java/compaction/compaction-job-creation-lambda/**'
      - 'java/query/query-core/**'
      - 'java/ingest/ingest-runner/**'
      - 'java/compaction/compaction-status-store/**'
      - 'java/compaction/compaction-job-creation/**'
      - 'java/common/common-invoke-tables/**'
      - 'java/common/common-job/**'
      - 'java/ingest/ingest-status-store/**'
      - 'java/sketches/**'
      - 'java/compaction/compaction-core/**'
      - 'java/ingest/ingest-core/**'
      - 'java/statestore/**'
      - 'java/parquet/**'
      - 'java/configuration/**'
      - 'java/common/dynamodb-tools/**'
      - 'java/core/**'

jobs:
  chunk-workflow:
    uses: ./.github/workflows/chunk.yaml
    with:
      chunkId: cdk
